services:

  nginx:
    image: nginx:latest
    container_name: nginx

    ports:
      - "443:443"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro

    depends_on:
      - webapp1
      - webapp2

  webapp1:
    build: ./website
    container_name: webapp1
    ports:
      - "3000:3000"

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: portaldb
      DB_USER: postgres
      DB_PASSWORD: postgres

    depends_on:
      - postgres

  webapp2:
    build: ./webapp
    container_name: webapp2
    ports:
      - "8080:8080"

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: portaldb
      DB_USER: postgres
      DB_PASSWORD: postgres
      INSTANCE_NAME: Web_App_2
      EMAIL_PASSWORD: "pmpk zvvg mtut ajty"

    depends_on:
      - postgres

  postgres:
    image: postgres:17

    container_name: postgres

    environment:
      POSTGRES_DB: portaldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

volumes:
  postgres_data: