events { }

http {
    include mime.types;

    server {
        listen 443 ssl;

        ssl_certificate         /etc/nginx/certs/serverkey.crt;
        ssl_certificate_key     /etc/nginx/certs/serverkey.key;

        # Web App 1
        location /websitename/ {
            proxy_pass http://webapp1:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Web App 2 (portal)
        location /websitename/portal/ {
            proxy_pass http://webapp2:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /websitename/static/ {
            proxy_pass http://webapp2:8080/static/;
        }

        location /login {
            proxy_pass http://webapp2:8080/login;
        }
    }
}