events { }

http {
    include mime.types;

    server {
        listen 443;

        # Web App 1
        location /websitename/ {
            proxy_pass http://webapp1:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Web App 2 (portal)
        location /websitename/portal/ {
            proxy_pass http://webapp2:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}